### ISSUE TITLE
Header of the website

### ISSUE THREAD

**Issue by SophieMacadamia** [valeriupredoi/valeriupredoi.github.io#10]
Hi Valeriu, I've added the .png that would be the banner/header for the whole website (each sections). You can find it at:
[Banner_website_IS-ENES3.png](https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/images/Banner_website_IS-ENES3.png)
The resolution is 2375x625. Let us see if it works !

**Comment by valeriupredoi** [comment]
just saw this now :laughing: - I think it's good now @SophieMacadamia - oh and BTW I see only issues where I am explicitly tagged (like with @valeriupredoi ) or assigned on the right hand side (I usually filter these notifications since I am involved in a lot of GitHub repos, so I don't go crazy and my email keeps inboxing hehe)
